### ISSUE TITLE
Unable to start cassandra (JDK 11)

### ISSUE THREAD

**Issue by Sam2243** [nosan/embedded-cassandra#21] opened 2019-01-28 10:26 UTC
Hey there,

For one of the tests, I have to use embedded-cassandra of yours as I have done the migration of the project from JDK 8 to 11. I have put the annotation @EmbbededCassandra on one of the test class but I am getting the following exception. Can you give me some more insights what I have to do? I am using the test dependency only which u have mentioned. I am using Spring boot 2.x.x and JDK 11.

`Caused by: java.io.IOException: Cassandra Process is not alive. Please see logs for more details. Last (5) lines:
	[0.000s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/tmp/embedded-cassandra-b1948e73-cdf5-4284-8e55-35f6b958d600/apache-cassandra-3.11.3/bin/../logs/gc.log instead.
	intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
	Improperly specified VM option 'ThreadPriorityPolicy=42'
	Error: Could not create the Java Virtual Machine.
	Error: A fatal exception has occurred. Program will exit.
	at com.github.nosan.embedded.cassandra.local.DefaultCassandraProcess.throwException(DefaultCassandraProcess.java:366)
	at com.github.nosan.embedded.cassandra.local.DefaultCassandraProcess.lambda$await$1(DefaultCassandraProcess.java:272)
	at com.github.nosan.embedded.cassandra.local.WaitUtils.await(WaitUtils.java:48)
	at com.github.nosan.embedded.cassandra.local.DefaultCassandraProcess.await(DefaultCassandraProcess.java:270)
	at com.github.nosan.embedded.cassandra.local.DefaultCassandraProcess.start(DefaultCassandraProcess.java:172)
	at com.github.nosan.embedded.cassandra.local.LocalCassandra.startInternal(LocalCassandra.java:242)
	at com.github.nosan.embedded.cassandra.local.LocalCassandra.lambda$start$0(LocalCassandra.java:147)`

**Comment by nosan** [comment] 2019-01-28 11:11
Hey @Sam2243,
`Apache Cassandra` still doesn't support `JDK 11` :(

As a workaround I can propose you to have both `JDK 8` and `JDK 11` on your machine and set `javaHome` attribute via `@EmbeddedLocalCassandra` annotation.

```
@RunWith(SpringRunner.class)
@EmbeddedLocalCassandra(javaHome = "${JAVA8_HOME:}")
@SpringBootTest
public class MyTest {
}
```
Hope, it would help you :)

**Comment by tsmgodoi** [comment] 2019-01-28 12:31
I guess @nosan recommendation is the way to go for now.

**Comment by nosan** [comment] 2019-01-28 13:11
@tsmgodoi, @Sam2243 
May I close this issue?

**Comment by tsmgodoi** [comment] 2019-01-28 13:13
@nosan, I'm still having a problem while setting the javaHome. When I run a test which manipulates data on the cassandra, it just hangs. But I don't know, it might not be related to running in a different JDK than the test.

**Comment by Sam2243** [comment] 2019-01-28 13:13
@nosan Thanks for swift replies. Just one additional question. JDK 8 is in path variables in intellij. Do I have to add the path variable name there or the full path itself?

@EmbeddedLocalCassandra(javaHome = "${JAVA8_HOME:}")

**Comment by Sam2243** [comment] 2019-01-28 13:14
@tsmgodoi Can you tell me how you set the java home? can you please paste the annotation itself here?

**Comment by tsmgodoi** [comment] 2019-01-28 13:15
@Sam2243 
For now I'm setting it manually:
@EmbeddedLocalCassandra(javaHome = "C:\\Program Files\\Java\\jdk1.8.0_162")
public abstract class ModulosApplicationIntegrationTest {
But I'll set it using a spring property on my application.yml when I get it running.

**Comment by nosan** [comment] 2019-01-28 13:44
@Sam2243 
Currently, it is difficult to say, but could you set `replace` attribute as `NONE` ? 
`@EmbeddedLocalCassandra(.., replace = EmbeddedCassandra.Replace.NONE)`

**P.S.** I would be appreciated if you create a separate `issue` with a small sample to reproduce this behaviour, seems like it is an unrelated issue to this one.
Thanks in advance

**Comment by Sam2243** [comment] 2019-01-28 13:45
@nosan 

Sure. Makes sense :) you may close this issue of course :)

**Comment by tsmgodoi** [comment] 2019-01-28 13:45
@nosan The hanging was not related to embedded cassandra. I just ran another test and it worked just fine. For me it's problem solved.

**Closed** 2019-01-28 13:46 UTC
Labels: question

**Comment by samuraisam** [comment] 2019-07-02 06:55
Has the `javaHome` parameter been removed in recent versions?

**Comment by nosan** [comment] 2019-07-02 07:13
`@EmbeddedLocalCassandra` has been removed in `2.X.X`.
Since `2.X.X` `CassandraFactoryCustomizer` can be used:

```java
@ExtendWith(SpringExtension.class)
@ContextConfiguration
@EmbeddedCassandra
class EmbeddedCassandraJavaTests {

	@Configuration
	static class JavaEightConfiguration {

		@Bean
		public CassandraFactoryCustomizer<LocalCassandraFactory> javaHomeCustomizer(
				@Value("${JAVA8_HOME:}") Path javaHome) {
			return factory -> factory.setJavaHome(javaHome);
		}

	}

}
```
